### ISSUE TITLE
新版1.23.0-alpha.18 关闭权限集中user 查看所有记录功能 不生效

### ISSUE THREAD

**Issue by 1113211631** [steedos/steedos-app-contract#66]
1.23.0-alpha.18版本中，
 问题一：在权限集里默认就是关闭查看所有记录的，但是发现 创建一个人员，简档设置为user ,  登录这个普通用户发现可以看到其他人的合同信息，  
![image](https://user-images.githubusercontent.com/42466618/105012862-94dd3600-5a79-11eb-8a38-09018314b99f.png)

问题二： 列表视图中过滤条件不生效，问题截图

![image](https://user-images.githubusercontent.com/42466618/105008353-1631ca00-5a74-11eb-8000-30b36d2be65d.png)

**Comment by 1113211631** [comment]
再补充一个问题， 新版界面在对象中新增列表视图， 保存后在 对象的 列表视图中看不到，  但是可以在 合同界面点击新增的视图 

![image](https://user-images.githubusercontent.com/42466618/105011008-63636b00-5a77-11eb-98e2-0da1537907b7.png)
![image](https://user-images.githubusercontent.com/42466618/105011038-6bbba600-5a77-11eb-820d-591beca22280.png)

**Comment by hotlong** [comment]
问题三，对象管理界面只会显示共享的视图。

**Comment by 1113211631** [comment]
> 问题三，对象管理界面只会显示共享的视图。

好的，感谢

**Comment by yinlianghui** [comment]
问题二： @1113211631 这个截图我看不出问题，你是在哪里配置的过滤条件，配置了什么条件？

**Comment by 1113211631** [comment]
> 问题二： @1113211631 这个截图我看不出问题，只看到过滤结果不对，你是在哪里配置的过滤条件，配置了什么条件？

我没加过滤条件 ，是默认的过滤条件就是错误的，  正常默认审批中合同是 审批状态为进行中， 这个问题我对照了1.22.10这个版本改了filters信息，已经好了，  

![image](https://user-images.githubusercontent.com/42466618/105146480-0335fd00-5b3b-11eb-847a-71703b58c62b.png)
这个截图是1.22.10的截图，  新版本是没有!<tag:yaml.org,2002:js/function>  这一段了，   我在新版本里加了这一段就生效了，

**Comment by 1113211631** [comment]
> > 问题二： @1113211631 这个截图我看不出问题，只看到过滤结果不对，你是在哪里配置的过滤条件，配置了什么条件？
> 
> 我没加过滤条件 ，是默认的过滤条件就是错误的， 正常默认审批中合同是 审批状态为进行中， 这个问题我对照了1.22.10这个版本改了filters信息，已经好了，
> 
> ![image](https://user-images.githubusercontent.com/42466618/105146480-0335fd00-5b3b-11eb-847a-71703b58c62b.png)
> 这个截图是1.22.10的截图， 新版本是没有!tag:yaml.org,2002:js/function 这一段了， 我在新版本里加了这一段就生效了，

现在主要麻烦您那边查一下 user的查看合同所有记录这个权限问题吧  这个问题比较重要

**Comment by yinlianghui** [comment]
> > > 问题二： @1113211631 这个截图我看不出问题，只看到过滤结果不对，你是在哪里配置的过滤条件，配置了什么条件？
> > 
> > 
> > 我没加过滤条件 ，是默认的过滤条件就是错误的， 正常默认审批中合同是 审批状态为进行中， 这个问题我对照了1.22.10这个版本改了filters信息，已经好了，
> > ![image](https://user-images.githubusercontent.com/42466618/105146480-0335fd00-5b3b-11eb-847a-71703b58c62b.png)
> > 这个截图是1.22.10的截图， 新版本是没有!tag:yaml.org,2002:js/function 这一段了， 我在新版本里加了这一段就生效了，
> 
> 现在主要麻烦您那边查一下 user的查看合同所有记录这个权限问题吧 这个问题比较重要

问题一：应该是你这个用户还属性其他权限集了，目前计算当前用户有哪些权限是通过叠加当前用户所属简档及其所属的所有权限集上的权限，并最终取最大权限的。

**Comment by 1113211631** [comment]
> 问题一：应该是你这个用户还属性其他权限集了，目前计算当前用户有哪些权限是通过叠加当前用户所属简档及其所属的所有权限集上的权限，并最终取最大权限的。
> 问题二： @1113211631 这个截图我看不出问题，只看到过滤结果不对，你是在哪里配置的过滤条件，配置了什么条件？

问题一： 我是给两个普通user加到permission_set_contract_manager 这个权限集了，  但是其他普通用户 只有一个user呀，我测试用了其他普通用户都登录了 都可以看到所有合同记录

**Comment by 1113211631** [comment]
> > 问题一：应该是你这个用户还属性其他权限集了，目前计算当前用户有哪些权限是通过叠加当前用户所属简档及其所属的所有权限集上的权限，并最终取最大权限的。
> > 问题二： @1113211631 这个截图我看不出问题，只看到过滤结果不对，你是在哪里配置的过滤条件，配置了什么条件？
> 
> 问题一： 我是给两个普通user加到permission_set_contract_manager 这个权限集了， 但是其他普通用户 只有一个user呀，我测试用了其他普通用户都登录了 都可以看到所有合同记录

我新装了一个平台，数据库也是新的，只有一个管理员与一个普通用户  我用管理员创建的合同，普通用户也可以看到，   user的查看所有记录是关闭的,

**Comment by 1113211631** [comment]
https://github.com/steedos/steedos-app-contract/releases/tag/v1.23.0-alpha.14 我下载的是这个软件包

**Comment by baozhoutao** [comment]
问题一是由于系统bug导致。下个版本修复：https://github.com/steedos/steedos-platform/issues/1396

**Comment by yinlianghui** [comment]
问题二也已经修正，新版本内核转换yml文件中新格式的视图过滤器函数有bug，已把相关函数还原为老版本了。
另外内核转换yml文件中新版本格式的过滤器函数也已经修正，待下个版本发包后可以用。
